### ISSUE TITLE
Rating, Review and Status validation

### ISSUE THREAD

**Issue by DNYLA** [sbondCo/Watcharr#114] opened 2023-08-21 18:29 UTC
Validation needs to be added onto the input for a review. When focus leaves the input a post request is made to the server without checking for any changes. You can see in the last image my thoughts changes has been spammed even though i didn't actually change anything. 
![image](https://github.com/sbondCo/Watcharr/assets/22224922/cf59907b-43e2-42d1-8417-7e814354c1a3)
![image](https://github.com/sbondCo/Watcharr/assets/22224922/dc8d92a8-bec5-495b-962e-a78ad78b41ae)

**Comment by IRHM** [comment] 2023-08-21 18:35
Dupe of #86 but I like your screenshots so I'll keep this one open.

#86 Issue:
>Currently if you update (for example) the rating of a show to the same as current rating, it will actually send a request to the server.
>
>Frontend shouldn't send a request if changing to same as current and backend should reject the request if value hasn't changed.

**Closed as completed** 2024-01-07 01:04 UTC
Labels: bug, good first issue
